apiVersion: v1
kind: ConfigMap
metadata:
  name: event-bus-config
data:
  JWT_SECRET: "rzz99wLqZDLmrdS&1JHRhyV&crj@DB"
  MONGODB_URI: "mongodb+srv://baguncadomonstrao:%23CabecaDoVandeco%40321@cluster-smartfarm.xailfpc.mongodb.net/smartfarm?retryWrites=true&w=majority&appName=Cluster-SmartFarm"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-bus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-bus
  template:
    metadata:
      labels:
        app: event-bus
    spec:
      containers:
        - name: event-bus
          image: event_bus:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3004
          resources:
            limits:
              memory: 256Mi
              cpu: 1
            requests:
              memory: 128Mi
              cpu: 250m
          envFrom:
            - configMapRef:
                name: event-bus-config

---
apiVersion: v1
kind: Service
metadata:
  name: event-bus
spec:
  type: ClusterIP
  selector:
    app: event-bus
  ports:
    - protocol: TCP
      port: 3004
      targetPort: 3004
