version: "3.9"

services:
  event_bus:
    build: ./event_bus
    container_name: event_bus
    ports:
      - "3004:3004"
    networks:
      - smartfarm
    env_file:
      - ./event_bus/.env
    dns:
      - 8.8.8.8
      - 8.8.4.4
      
  user_mss:
    build: ./user_mss
    container_name: user_mss
    ports:
      - "3000:3000"
    depends_on:
      - event_bus
    networks:
      - smartfarm
    env_file:
      - ./user_mss/.env
    dns:
      - 8.8.8.8
      - 8.8.4.4

  sensor_mss:
    build: ./sensor_mss
    container_name: sensor_mss
    ports:
      - "3001:3001"
    depends_on:
      - event_bus
    networks:
      - smartfarm
    env_file:
      - ./sensor_mss/.env
    dns:
      - 8.8.8.8
      - 8.8.4.4

  reading_mss:
    build: ./reading_mss
    container_name: reading_mss
    ports:
      - "3002:3002"
    depends_on:
      - event_bus
    networks:
      - smartfarm
    env_file:
    - ./reading_mss/.env
    dns:
      - 8.8.8.8
      - 8.8.4.4

  view_mss:
    build: ./view_mss
    container_name: view_mss
    ports:
      - "3003:3003"
    depends_on:
      - event_bus
    networks:
      - smartfarm
    env_file:
      - ./view_mss/.env
    dns:
      - 8.8.8.8
      - 8.8.4.4

networks:
  smartfarm:
    driver: bridge
